kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-checker
  namespace: prod
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/status", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleaner
  namespace: kube-system
rules:
- apiGroups: ["apps"]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "exec", "list", "create"]
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "exec", "list", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-checker-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: prod
roleRef:
  kind: ClusterRole
  name: deployment-checker
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleaner-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cleaner
  apiGroup: rbac.authorization.k8s.io
