apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:47cce3379352acf760427f0fb9a0368ebbb46d30daa7f44e3ae8bdb0e99220fc
  name: docker.clrn.dev/crypto-ml
  newName: docker.clrn.dev/crypto-ml
- digest: sha256:8e575709d23600676c4de0387cc09568f4e2ff2b73f8f5e8f167efd468b7b21f
  name: docker.clrn.dev/crypto-ml-gpu
  newName: docker.clrn.dev/crypto-ml-gpu
- digest: sha256:0a25f03ea321c74bffb717d85b7c0b922384004fb274c74eb6598ca4e2d471f3
  name: docker.clrn.dev/postgres
  newName: docker.clrn.dev/postgres
- digest: sha256:9a27b264c17d7bf13eabe94f3a0c1f7aad39979f124c9cd503c0dd7fae78fc65
  name: docker.clrn.dev/waiter
  newName: docker.clrn.dev/waiter
#- resources/ann-worker.yaml
resources:
- resources/trainer.yaml
- resources/trader.yaml
- resources/rbac.yaml
- resources/grafana.yaml
- resources/postgres.yaml
- resources/zk.yaml
- resources/price-worker.yaml
- resources/deals-worker.yaml
- resources/background-processing.yaml
- resources/backup.yaml
- resources/status-bot.yaml
