{
 "title": "Cluster Load",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "tags": [
  "monitoring",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{}"
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_GPU_UTIL{})" }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_FB_USED{})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP{})" }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE{})" }
   ]
  },
  {
   "title": "Running pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{service=\"kubelet\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{namespace=\"prod\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_GPU_UTIL{})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_POWER_USAGE{})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_GPU_TEMP{})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_FB_USED{})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (gpu) (DCGM_FI_DEV_SM_CLOCK{} * 1000000)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Alerts History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group(ALERTS{namespace=\"prod\"}) by (alertname, alertstate, deployment, pod)",
     "legendFormat": "{{deployment}} {{pod}} - {{alertname}} {{alertstate}}"
    }
   ]
  }
 ]
}