{
 "title": "Deals",
 "tags": [ "crypto" ],
 "time": { "from": "2021-11-01T00:00:00.000Z", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "currency",
    "query": "select code __value from currency order by code"
   },
   { "name": "version", "query": "select id __value from version" },
   {
    "name": "individual",
    "query": "select md5 as __value, md5 as __text from individual"
   },
   {
    "name": "deal_limit",
    "query": "1, 2, 3, 4, 5, 10,  20, 50, 100, 200, 300, 400, 500, 1000, 10000"
   }
  ]
 },
 "panels": [
  {
   "title": "Running sum and $currency price (USD)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select ts as \"time\",\n       close\n  from price\n where 1 = 1 \n   and currency = '$currency'\n   and $__timeFilter(ts)\n order by ts"
    },
    {
     "rawSql": "select dt.buy_ts as \"time\",\n       dt.usd     as rs,\n       '[ ' || dt.version_id::text || ' - ' || dt.md5 || ' ]' as md5\n  from get_run_sum_deals_by_minute_tab('$currency', array[$version], array[$individual], $__timeFrom(), $__timeTo()) dt\n order by dt.buy_ts"
    }
   ]
  },
  {
   "title": "Top ",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with deals as\n(\n    select d.currency,\n           d.version,\n           d.individual as ind_id,\n           i.md5,\n           i.parent_md5,\n           d.id as deal_id,\n           --\n           row_number() over (partition by d.currency, d.version, d.individual order by d.buy_ts) as rn,\n           count(*) over (partition by d.currency, d.version, d.individual) as rc,\n           --\n           d.buy_ts,\n           d.buy_price,\n           --\n           case\n               -- if a deal is open at the end of the interval\n               -- we set sell_ts as the end of the interval\n               when d.sell_price is null then\n                   1\n               else\n                   0\n           end as is_sell_open,\n           case\n               -- if a deal is open at the end of the interval\n               -- we set sell_ts as the end of the interval\n               when d.sell_price is null then\n                   date_trunc('minute', $__timeTo()::timestamp)\n               else\n                   d.sell_ts\n           end as sell_ts,\n           case\n               -- if a deal is open at the end of the interval\n               -- we get the price for the end of the interval\n               when d.sell_price is null then\n                   (\n                       select close\n                         from price p\n                        where 1 = 1\n                          and p.currency = d.currency\n                          and p.ts = date_trunc('minute', $__timeTo()::timestamp)\n                   )\n               else\n                   d.sell_price\n           end as sell_price,\n           -- \n           d.run_usd,\n           d.run_crypto,\n           d.run_percent,\n           i.is_portfolio\n      from deal d,\n           individual i\n     where 1 = 1\n       and d.currency = '$currency'\n       and d.version = any(array[$version]::int[])\n       and d.individual = i.id\n       and (\n               (d.buy_ts between $__timeFrom() and $__timeTo() or d.buy_ts < $__timeTo() and coalesce(d.sell_ts,$__timeTo()) between $__timeFrom() and $__timeTo())\n               or\n               ($__timeFrom() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) and $__timeTo() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) )\n           )\n),\ndeals_res as\n(\n    select d.currency,\n           d.version,\n           d.ind_id,\n           d.md5,\n           d.parent_md5,\n           --\n           d.rn,\n           d.rc,\n           max(d.is_sell_open) over(partition by d.currency, d.version, d.ind_id) is_open_deals,\n           --\n           d.buy_ts,\n           d.buy_price,\n           --\n           d.is_sell_open,\n           d.sell_ts,\n           d.sell_price,\n           -- res\n           coalesce((d.sell_price*0.999 - d.buy_price*1.001), 0) as deal_res,\n           case\n             when extract(epoch from (d.sell_ts - d.buy_ts))/3600 < 0/60 then\n                   least(coalesce((d.sell_price*0.999 - d.buy_price*1.001)/d.buy_price * 100, 0), 0)\n               else\n                   coalesce((d.sell_price*0.999 - d.buy_price*1.001)/d.buy_price * 100, 0)\n           end as deal_res_percent,\n           --\n           extract(epoch from (d.sell_ts - d.buy_ts))/3600  as in_hours,\n           extract(epoch from ($__timeTo()::timestamp - $__timeFrom()::timestamp))/3600 as total_hours,\n           --\n           case\n               when coalesce((d.sell_price*0.999 - d.buy_price*1.001), 0) > 0 then\n                  1\n               else\n                  0\n           end as is_pos_deal_res,\n           case\n               when coalesce((d.sell_price*0.999 - d.buy_price*1.001), 0) <= 0 then\n                  1\n               else\n                  0\n           end as is_neg_deal_res,\n           --\n           d.run_crypto,\n           d.run_usd,\n           d.run_percent,\n           d.is_portfolio\n      from deals d\n)\n,groupped as\n(\n    select dr.currency,\n           dr.version,\n           dr.ind_id,\n           dr.md5,\n           dr.parent_md5,\n           --\n           sum(dr.is_pos_deal_res)          as pos_deals_cnt,\n           sum(dr.is_neg_deal_res)          as neg_deals_cnt,\n           count(*)                         as deals_cnt,\n           --\n           sum(in_hours)                    as in_hours,\n           min(total_hours) - sum(in_hours) as out_hours,\n           min(total_hours)                 as total_hours,\n           --\n           min(dr.deal_res_percent)         as min_perc,\n           avg(dr.deal_res_percent)         as avg_perc,\n           max(dr.deal_res_percent)         as max_perc,\n           --\n           max(\n               case\n                   when is_open_deals = 1 and dr.rn = dr.rc - 1 then\n                       dr.run_crypto\n                   when is_open_deals = 0 and dr.rn = dr.rc then\n                       dr.run_crypto\n                   else\n                       null\n               end\n           ) as run_crypto,\n           max(\n               case\n                   when is_open_deals = 1 and dr.rn = dr.rc - 1 then\n                       dr.run_usd\n                   when is_open_deals = 0 and dr.rn = dr.rc then\n                       dr.run_usd\n                   else\n                       null\n               end\n           ) as run_usd,\n           max(\n               case\n                   when is_open_deals = 1 and dr.rn = dr.rc - 1 then\n                       dr.run_percent\n                   when is_open_deals = 0 and dr.rn = dr.rc then\n                       dr.run_percent\n                   else\n                       null\n               end\n           ) as run_percent,\n           max(dr.is_portfolio) as is_portfolio\n      from deals_res dr\n     where 1 = 1\n     group by dr.currency,\n           dr.version,\n           dr.ind_id,\n           dr.md5,\n           dr.parent_md5\n),\nall_data as\n(\n\tselect row_number() over(partition by dt.currency_code, dt.version_id, dt.individual_id order by dt.buy_ts desc) as rn,\n\t       dt.*,\n\t       --\n\t       g.pos_deals_cnt,\n\t       g.deals_cnt,\n\t       g.in_hours,\n\t       g.out_hours,\n\t       g.total_hours,\n\t       --\n\t       g.min_perc,\n\t       g.avg_perc,\n\t       g.max_perc,\n\t       g.parent_md5,\n\t       g.is_portfolio\n\t  from groupped g,\n\t       get_run_sum_deals_tab\n\t       (\n\t\t        p_currency_code := g.currency,\n    \t\t    p_version_arr   := array[g.version::text],\n    \t\t    p_individ_id    := g.ind_id,\n    \t\t    p_start_ts      := $__timeFrom()::timestamp,\n    \t\t    p_end_ts        := $__timeTo()::timestamp,\n    \t\t    p_is_debug      := 0\n\t       ) dt\n\t where g.ind_id = dt.individual_id\n)\nselect row_number() over(order by ad.percent desc nulls last, ad.parent_md5 nulls first) as \"#\",\n       ad.version_id as \"Ver\",\n       ad.md5 as \"Individual md5\",\n       ad.is_portfolio as \"Portf\",\n       ad.percent as \"Run %\",\n       --\n       ad.deals_cnt   as \"Deals\",\n       ad.pos_deals_cnt::float / ad.deals_cnt * 100  as \"+ deals %\",\n       ad.in_hours / ad.total_hours * 100 as \"In %\",\n       -- ad.out_hours / ad.total_hours * 100 as \"Out %\",\n       --\n       ad.min_perc    as \"Min %\",\n       ad.avg_perc    as \"Avg %\",\n       ad.max_perc    as \"Max %\"--,\n       --ad.parent_md5  as \"Parent\",\n  from all_data ad\n where rn = 1"
    }
   ]
  },
  {
   "title": "Portfolio",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with members as\n(\n    select q.*\n      from \n           (\n               select i.md5,\n                      --\n                      d.buy_ts,\n                      d.buy_price,\n                      d.sell_ts,\n                      d.sell_price,\n                      case\n                          when sell_ts is null then\n                              1\n                          else\n                              null\n                      end as is_in_deal,\n                      --\n                      row_number() over (partition by d.currency, d.version, d.individual order by d.buy_ts) as rn,\n                      count(*) over (partition by d.currency, d.version, d.individual) as rc\n                 from deal d,\n                      individual i\n                where 1 = 1\n                  and d.currency = '$currency'\n                  and d.version = any(array[$version]::int[])\n                  and d.individual = i.id\n                  and i.md5 in (select md5 from portfolio p where p.portfolio_md5 in ($individual))\n                  and (\n                          (d.buy_ts between $__timeFrom() and $__timeTo() or d.buy_ts < $__timeTo() and coalesce(d.sell_ts,$__timeTo()) between $__timeFrom() and $__timeTo())\n                          or\n                          ($__timeFrom() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) and $__timeTo() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) )\n                      )\n           ) q\n     where q.rn = q.rc\n),\nportfolio as\n(\n    select row_number() over(partition by p.portfolio_md5 order by p.md5, m.buy_ts desc) as prn,\n           p.portfolio_md5,\n           p.md5,\n           m.buy_ts,\n           m.buy_price,\n           m.sell_ts,\n           m.sell_price,\n           m.is_in_deal\n      from portfolio p\n left join members m\n        on p.md5 = m.md5\n     where 1 = 1 \n       and p.portfolio_md5 in ($individual)\n)\nselect case\n           when p.prn = 1 then\n               p.portfolio_md5\n           else\n               null\n       end as portfolio_md5,\n       p.md5,\n       p.sell_ts as \"Last Sell Date\",\n       p.sell_price as \"Last Sell Price\",\n       p.is_in_deal as \"In?\"\n  from portfolio p\n order by p.portfolio_md5,\n       p.md5,\n       p.buy_ts desc"
    }
   ]
  },
  {
   "title": "Deals",
   "type": "table",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with q as \n(\n  select row_number() over(partition by dt.currency_code, dt.version_id, dt.individual_id order by dt.buy_ts desc) as \"#\",\n         dt.version_id as \"Ver\",\n         dt.md5,\n        i.is_portfolio as \"Portfolio\",\n         dt.buy_price as \"Buy Price\",\n         dt.sell_price as \"Sell Price\",\n         coalesce((dt.sell_price*0.999 - dt.buy_price*1.001), 0) as \"Deal Res USD\",\n         coalesce((dt.sell_price*0.999 - dt.buy_price*1.001)/dt.buy_price * 100, 0) as \"Deal Res %\",\n         dt.buy_ts as \"Buy Date\",\n         dt.sell_ts as \"Sell Date\",\n         dt.usd as \"Run USD\",\n         dt.percent as \"Run %\",\n         dt.individual_id as \"Individual ID\",\n         dt.id as \"Deal ID\"\n    from individual i,\n         get_run_sum_deals_tab('$currency', array[$version], i.id, $__timeFrom(), $__timeTo()) dt\n   where 1 = 1\n     and i.md5 in ($individual)\n     and i.md5 = dt.md5\n)\nselect * from q where \"#\" <= $deal_limit"
    }
   ]
  },
  {
   "title": "Difference Running sum and $currency price (USD)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  0 as \"$currency\"\nFROM price\nWHERE currency = '$currency'\n  and $__timeFilter(ts)\nORDER BY 1"
    },
    {
     "rawSql": "with deals as\n(\nselect dt.version_id,\n       dt.md5,\n       case\n           -- if a deal is open at the end of the interval\n           -- we set sell_ts as the end of the interval\n           when dt.sell_price is null then\n               date_trunc('minute', $__timeTo()::timestamp)\n           else\n               dt.sell_ts\n       end as sell_ts,\n       dt.usd     as run_usd\n  from get_run_sum_deals_by_minute_tab('$currency', array[$version], array[$individual], $__timeFrom(), $__timeTo()) dt\n)\n    select p.ts as \"time\",\n           d.run_usd - p.close as diff,\n           '[ ' || d.version_id::text || ' - ' || d.md5 || ' ]' as md5\n      from deals d,\n           price p\n     where d.sell_ts = p.ts\n       and p.currency = '$currency'\n     order by p.ts"
    }
   ]
  },
  {
   "title": "Deals percent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  0 as \"$currency\"\nFROM price\nWHERE currency = '$currency'\n  and $__timeFilter(ts)\nORDER BY 1"
    },
    {
     "rawSql": "with deals as\n(\n    select d.currency,\n           d.version,\n           d.individual as ind_id,\n           i.md5,\n           --\n           d.buy_ts,\n           d.buy_price,\n           --\n           case\n               -- if a deal is open at the end of the interval\n               -- we set sell_ts as the end of the interval\n               when d.sell_price is null then\n                   date_trunc('minute', $__timeTo()::timestamp)\n               else\n                   d.sell_ts\n           end as sell_ts,\n           case\n               -- if a deal is open at the end of the interval\n               -- we get the price for the end of the interval\n               when d.sell_price is null then\n                   (\n                       select close\n                         from price p\n                        where p.currency = d.currency\n                          and p.ts = date_trunc('minute', $__timeTo()::timestamp)\n                   )\n               else\n                   d.sell_price\n           end as sell_price\n      from deal d,\n           individual i\n     where 1 = 1\n       and d.currency = '$currency'\n       and d.version = any(array[$version]::int[])\n       and d.individual = i.id\n       and i.md5 in ($individual)\n       and (\n               (d.buy_ts between $__timeFrom() and $__timeTo() or d.buy_ts < $__timeTo() and coalesce(d.sell_ts,$__timeTo()) between $__timeFrom() and $__timeTo())\n               or\n               ($__timeFrom() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) and $__timeTo() between d.buy_ts and coalesce(d.sell_ts,$__timeTo()) )\n           )\n),\ndeals_res as\n(\n    select d.currency,\n           d.version,\n           d.ind_id,\n           d.md5,\n           --\n           d.buy_ts,\n           d.buy_price,\n           --\n           d.sell_ts,\n           d.sell_price,\n           -- res\n           coalesce((d.sell_price*0.999 - d.buy_price*1.001), 0) as deal_res,\n           coalesce((d.sell_price*0.999 - d.buy_price*1.001)/d.buy_price * 100, 0) as deal_res_percent\n      from deals d\n)\nselect sell_ts as \"time\",\n       deal_res_percent as deal_perc,\n       '[ ' || dr.version::text || ' - ' || dr.md5 || ' ]' as md5\n  from deals_res dr \n where 1 = 1 \n order by sell_ts"
    }
   ]
  }
 ]
}